package:
  name: pdfsplitter
  version: 0.0.2
source:
  sha256: 9f4e0c0b0387391f170776dfce19d02b9d00300fd6b31cab346748266c7f8e0d
  url: https://files.pythonhosted.org/packages/cf/e3/24c19a72c01e7c04e51378d3084ca16c19641c7d8ae593b66019536dbd58/pdfsplitter-0.0.2.tar.gz
about:
  dev_url: https://strickvl.github.io
  doc_url: https://strickvl.github.io
  home: https://strickvl.github.io
  license: Apache Software
  license_family: APACHE
  summary: Turn PDFs into image files for use in machine learning projects
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - strickvl
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - pdfsplitter
