# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pdf_to_img": "00_core.ipynb",
         "extract_images_from_pdfs": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://strickvl.github.io/pdfsplitter/"

git_url = "https://github.com/strickvl/pdfsplitter/tree/main/"

def custom_doc_links(name): return None
