# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pdf_to_img": "00_core.ipynb",
         "extract_images_from_pdfs": "00_core.ipynb",
         "say_name": "00_core.ipynb",
         "get_page_count": "01_stats.ipynb",
         "get_file_metadata": "01_stats.ipynb",
         "add_comma_separation": "01_stats.ipynb",
         "has_ocr_layer": "01_stats.ipynb",
         "get_stats": "01_stats.ipynb",
         "convert_timestamp": "01_stats.ipynb",
         "get_json_stats": "01_stats.ipynb",
         "get_dataframe_stats": "01_stats.ipynb",
         "export_stats_as_csv": "01_stats.ipynb",
         "display_stats": "01_stats.ipynb",
         "add_scheme_and_domain": "02_scraper.ipynb",
         "get_pdf_links": "02_scraper.ipynb",
         "download_pdf_files": "02_scraper.ipynb"}

modules = ["core.py",
           "stats.py",
           "scraper.py"]

doc_url = "https://strickvl.github.io/pdfsplitter/"

git_url = "https://github.com/strickvl/pdfsplitter/tree/main/"

def custom_doc_links(name): return None
