# AUTOGENERATED! DO NOT EDIT! File to edit: 01_stats.ipynb (unless otherwise specified).

__all__ = ['get_page_count', 'add_comma_separation', 'get_stats']

# Cell
import os
from pathlib import Path
from typing import Any
import fitz

from rich import print
from rich.console import Console
from rich.table import Table

# Cell
def get_page_count(filepath: "os.PathLike[Any]") -> int:
    """Gets the page count of a PDF file."""
    pdf_obj = fitz.open(filepath)
    return pdf_obj.page_count

# Cell
def add_comma_separation(input: int) -> str:
    """Adds comma-separation for thousands to an integer."""
    return f'{input:,.0f}'

# Cell
def get_stats(source_path: "os.PathLike[Any]") -> int:
    """Displays statistics on the PDF data contained in a particular repository."""
    table = Table(title="Stats for your PDF Files")

    table.add_column("PageCount", justify="right", style="green")
    table.add_column("Filename", justify="left", style="cyan", no_wrap=True, max_width=50)


    count = 0
    file_number = 0
    files = list(source_path.glob("**/*.pdf")) # searches source_path and all subfolders
    for file in files:
        file_number += 1
        current_file_count = get_page_count(file)
        count += current_file_count
        if file_number <= 45:
            table.add_row(str(current_file_count), file.name)

    if file_number > 45:
        table.add_row("...", "...")

    console = Console()
    console.print(table)

    bold_str_count = f"[bold red]{add_comma_separation(count)}"
    console.print("[bold red]TOTAL PAGECOUNT:", bold_str_count)